Ration_Django_Web_App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('ration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ration/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('', views.home, name='home'), #**kwargs, key word argument
    path('about/', views.about, name='about'),
    path('recipes/', views.recipes_index, name='index'),
    path('recipes/<int:recipe_id>/', views.recipes_detail, name="detail"),
    path('recipes/<int:recipe_id>/favorite/', views.favorite_recipe, name="favorite_recipe"),
    path('recipes/<int:recipe_id>/unfavorite/', views.unfavorite_recipe, name="unfavorite_recipe"),
    path('recipes/<int:recipe_id>/delete_recipe', views.delete_recipe, name='delete_recipe'),
    path('recipes/<int:recipe_id>/add_review/', views.add_review, name='add_review'),
    path('recipes/<int:recipe_id>/update/', views.recipe_update, name='update'),
    path('recipes/<int:recipe_id>/remove_review/<int:review_id>/', views.remove_review, name='remove_review'),
    path('recipes/create/', views.recipe_create, name='recipe_create'),
    path('recipes/search/', views.recipes_search, name='recipes_search'),
    path('accounts/signup/', views.signup, name='signup'),
    path('members/<int:user_id>/profile/', views.profile_detail, name='profile_detail'),
    path('members/profile', views.my_profile, name='my_profile'),
    path('members/profile/update', views.profile_update, name="profile_update"),
    path('members/profile/change_password', views.change_password, name="change_password"),
    path('members/profile/<int:date>', views.meal_log, name='meal_log'),
    path('meals', views.meal_search, name='meal_search'),
    path('meals/<int:recipe_id>/create', views.meal_create, name='meal_create'),
    path('meals/delete/<int:meal_id>', views.meal_delete, name="meal_delete"),
    path('review/<int:review_id>/update_review/', views.update_review, name='update_review'),
]


urlpatterns += staticfiles_urlpatterns()

ration/models.py
from django.db import models
from django.db.models import Avg
from datetime import date
from django.urls import reverse 
from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.validators import MaxValueValidator, MinValueValidator
import operator
import datetime

class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    calorie = models.FloatField(validators=[MinValueValidator(0.0)])
    carbohydrate = models.FloatField(validators=[MinValueValidator(0.0)])
    fat = models.FloatField(validators=[MinValueValidator(0.0)])
    protein = models.FloatField(validators=[MinValueValidator(0.0)])
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Recipe(models.Model):
    title = models.CharField(max_length=50)
    summary = models.TextField(max_length=500)
    directions = models.TextField()
    cooking_minutes = models.IntegerField(validators=[MinValueValidator(0)])
    preparation_minutes = models.IntegerField(validators=[MinValueValidator(0)])
    image = models.CharField(null=True, blank=True, max_length=200)
    servings = models.IntegerField(validators=[MinValueValidator(1)])
    ingredient = models.ManyToManyField(Ingredient, through='Amount')
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    date_added = models.DateTimeField(auto_now_add=True)

    def average_rating(self) -> float:
        return Review.objects.filter(recipe=self).aggregate(Avg("rating"))["rating__avg"] or 0

    def get_star_rating(self):
        return range(0, int(self.average_rating()))

    def calculate_nutrition(self):
        nutrient = {}
        for ingredient in Amount.objects.filter(recipe=self):
            for key, value in ingredient.ingredient.__dict__.items():
                if type(value) == float:
                    previous_amount = nutrient.get(key, 0)
                    size_multiplier = {
                        'S': 1/3 ,
                        'M': 1,
                        'L': 16,
                    }
                    nutrient[key] = previous_amount + value*ingredient.amount*size_multiplier.get(ingredient.size, 1)
        for key in nutrient:
            nutrient[key] /= self.servings 
        return nutrient

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'recipe_id': self.id})

SIZES = (
	('S', 'Teaspoon'),
	('M', 'Tablespoon'),
	('L', 'Cup'),
)

class Amount(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.FloatField(validators=[MinValueValidator(0.0)])
    size = models.CharField(
		max_length=1,
		# this will help us make a select menu when a form is created from this model
		choices=SIZES, 
		default=SIZES[1][0])

    def __str__(self):
        return f"{self.recipe}: {self.ingredient}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.CharField(null=True, blank=True, max_length=200)
    daily_calorie = models.FloatField(default=2000.0, validators=[MinValueValidator(0.0)])
    daily_carbohydrate = models.FloatField(default=300.0, validators=[MinValueValidator(0.0)])
    daily_fat = models.FloatField(default=65.0, validators=[MinValueValidator(0.0)])
    daily_protein = models.FloatField(default=50.0, validators=[MinValueValidator(0.0)])
    favorites = models.ManyToManyField(Recipe, blank=True)
    

    def __str__(self):
        return self.user.username

    def get_daily_nutrition(self, day, month, year):
        date = datetime.datetime(year, month, day)
        daily_meals = self.meal_set.filter(date=date)
        daily_nutrition = {}
        for meal in daily_meals:
            for nutrient, value in meal.recipe.calculate_nutrition().items():
                daily_nutrition[nutrient] = value + daily_nutrition.get(nutrient, 0)
    
    def fed_for_day(self, day, month, year):
        date = datetime.datetime(year, month, day)
        return self.meal_set.filter(date=date).count() >= len(MEALS) - 1

    @classmethod
    def count_favorites(cls):
        favorites = cls.favorites.through.objects.all()
        favorites_dictionary = {}
        for favorite in favorites:
            if favorite.recipe not in favorites_dictionary:
                favorites_dictionary[favorite.recipe] = 1
            else:
                favorites_dictionary[favorite.recipe] += 1
        return sorted(favorites_dictionary.items(), key=operator.itemgetter(1),reverse=True)[:3]

class Review(models.Model):
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    constraints = [
        models.UniqueConstraint(fields=['recipe', 'user'], name='unique_review_per_user')
    ]

MEALS = (
	('B', 'Breakfast'),
	('L', 'Lunch'),
	('D', 'Dinner'),
    ('S', 'Snack'),
)

class Meal(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    servings = models.FloatField(validators=[MinValueValidator(0.0)])
    meal = models.CharField(
		max_length=1,
		choices=MEALS, 
		default=MEALS[0][0])
    date = models.DateField('Meal date')

    def __str__(self):
        return f"{self.get_meal_display()} of {self.servings} servings {self.recipe.title} on {self.date}"
    
    def calculate_nutrition(self):
        nutrition = self.recipe.calculate_nutrition()
        for key, value in nutrition.items():
            nutrition[key] = value*self.servings
        return nutrition

ration/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Review, Ingredient, Amount, MEALS
import datetime

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2",] 

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class ReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=((1,1),(2,2),(3,3),(4,4),(5,5)))
    comment = forms.CharField(max_length=250)
    class Meta:
        model = Review
        fields = ['rating', 'comment']

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    daily_calorie = forms.FloatField(min_value=0)
    daily_carbohydrate = forms.FloatField(min_value=0)
    daily_fat = forms.FloatField(min_value=0)
    daily_protein = forms.FloatField(min_value=0)

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

class CreateRecipeForm(forms.Form):
    title = forms.CharField(max_length=50)
    summary = forms.CharField(widget=forms.Textarea,max_length=500)
    directions = forms.CharField(widget=forms.Textarea)
    cooking_minutes = forms.IntegerField(min_value=0)
    preparation_minutes = forms.IntegerField(min_value=0)
    servings = forms.IntegerField(min_value=1)

    def __init__(self, *args, **kwargs):
        super(CreateRecipeForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class MealForm(forms.Form):
    servings = forms.FloatField(min_value=0, initial=1.0)
    date = forms.DateField(widget=forms.SelectDateWidget(empty_label="Nothing"), initial=datetime.date.today)
    meal = forms.ChoiceField(choices=MEALS)

    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    

ration/templates/recipes/confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="shadow p-3 mb-5 bg-white rounded">
	<h3>Delete Recipe</h3>
	<br />
	<h6>Are you sure you want to delete <span class="text-primary">{{ recipe.title }} ?</span></h6>
	<br />
	<form action="" method="POST">
		{% csrf_token %}
		<input type="submit" value="Yes - Delete!" class="btn btn-primary">
		<a href="{% url 'detail' recipe.id%}"> <button type="button" class="btn btn-outline-primary"> Cancel</button></a>
	</form>
</div>

{% endblock content %}

ration/templates/recipes/create.html
{% extends 'base.html' %}


{% block content %}
<div>


<div id="form-add" class="shadow mb-8 bg-white rounded">
{% if recipe %}
	<h3>Edit Recipe <span class="teal-text">{{ recipe.name }}</span></h3>
{% else %}
	<h3>Add Recipe</h3>
{% endif %}

{% if error_message %}<p class="red-text">{{ error_message }}</p>{% endif %}
	

<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="file" name="photo-file">
	<br />
	<div class="d-flex justify-content-around align-items-start p-2 table-sm" cellspacing="0">
		<table id="ingredient-list" class="table">
			<colgroup>
				<col class="column_ingredient">
                <col class="column_data">
                <col class="column_data">
			</colgroup>
			<thead>
				<tr>
					<th class="th-sm">Ingredient</th>
					<th class="th-sm">Amount</th>
					<th class="th-sm">Size</th>
				</tr>
			</thead>
			<tbody>
				
				
				{% for ingredient in ingredients %}
				<tr data-id="{{ ingredient.ingredient.id }}">
					<td class="name">
						<button class="removeIngredient btn btn-light" type="button">X</button> <span>{{ ingredient.ingredient.name }}</span>
					</td>
					<td>
						<input type="number" class="form-control" step="0.01" name="amount-{{ ingredient.ingredient.id }}" value="{{ ingredient.amount }}" min="0" required="">
					</td>
					<td>
						<select class="form-control" name="size-{{ ingredient.ingredient.id }}" required="">
							
							{% for option in SIZES %}
								<option value="{{ option.0 }}" 
								{% if ingredient.size == option.0 %}
									selected="selected"
								{% endif %}
									>{{ option.1 }}</option>
							{% endfor %}
								
						</select>
					</td>
				</tr>	
				{% endfor %}
					
					
			</tbody>
		</table>
		<table id="ingredient-options" class="table table-hover table-striped table-bordered table-sm" cellspacing="0"
		width="100%">
		<thead>
			<tr>
			<th class="th-sm">Ingredient
			</th>
			</tr>
		</thead>
		<tbody>
			
			{% for ingredient in ingredient_list %}
				<tr class = "addIngredient" data-id="{{ ingredient.id }}">
					<td class="d-flex justify-content-between">
						<span>{{ ingredient.name }}</span> <button class="btn btn-light" type="button">+</button>
					</td>
				</tr>
			{% endfor %}
				
			</tbody>
		</table>
	</div>
	<input type="submit" value="Submit" class="btn btn-outline-primary">
	
</form>

</div>
</div>
<br />
<script>
	$(document).ready(function () {
		$('#ingredient-options').DataTable({
			"scrollY": "200px",
			"scrollCollapse": true,
		});
		$('.dataTables_length').addClass('bs-select');
		$('#ingredient-options_filter > input').addClass('form-control')
		$('.paginate_button').addClass('btn')
	});


	$('#ingredient-options').on('click', '.addIngredient', function(event) {
		row = $(this).closest('tr');
		$("#ingredient-list").find('tbody')
    	.append($(`<tr data-id=${row.data('id')}>
			<td class="name">
				<button class="removeIngredient btn btn-light" type="button">X</button> <span>${row.find('span').prop("innerText")}</span>
			</td>
			<td>
				<input type="number" class="form-control" step="0.01" name="amount-${row.data('id')}" min="0" required="">
			</td>
			<td>
				<select class="form-control" name="size-${row.data('id')}" required="">
					<option value="S">Teaspoons</option>
					<option value="M" selected>Tablespoons</option>
					<option value="L">Cups</option>
				</select>
			</td>
		</tr>`)
            )
		row.remove();
	});

	$('#ingredient-list').on('click', '.removeIngredient', function(event) {
		row = $(this).closest('tr');
		$('#ingredient-options').find('tbody')
		.append($(`<tr class = "addIngredient" data-id="${row.data('id')}">
					<td class="d-flex justify-content-between">
						<span>${row.find('span').text()}</span> <button class="btn btn-light" type="button">+</button>
					</td>
				</tr>`)
		);
		row.remove();
	})
</script>
{% endblock content %}

ration/templates/recipes/detail.html
{% extends 'base.html' %}
{% load ration_extras %}
{% block content %}


    <div class="card-deck mb-6 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h2 class="my-0 font-weight-normal">{{ recipe.title }} 
                {% if user.is_authenticated %}
                    {% if is_favorited %}
                        <a href="{% url 'unfavorite_recipe' recipe.id %}"><i class="fa fa-star"></i></a>
                    {% else %}
                        <a href="{% url 'favorite_recipe' recipe.id %}"><i class="fa fa-star-o"></i></a>
                    {% endif %}   
                {% endif %}</h2>
            </div>
            <div class="card-body">
                <div>
                    {% if recipe.image %}
                       <img class="img-thumbnail" src="{{ recipe.image }}" width="350">
                    {% endif%}
                    
                </div>
                <h1 class="card-title" >
                <small class="text-muted"></small>
               
                   
                </h1>
                <h2><span class="fa fa-star{% if recipe.average_rating < 1 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if recipe.average_rating < 2 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if recipe.average_rating < 3 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if recipe.average_rating < 4 %}-o {% endif %}" ></span>
            <span class="fa fa-star{% if recipe.average_rating < 5 %}-o {% endif %}"></span></h2>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Created by: <a href="{% url 'profile_detail' recipe.user.id %}">{{ recipe.user }}</a></li>
                    <li>Date added: {{ recipe.date_added|date:"Y-m-d" }}</li> <hr />
                    <a href="{% url 'meal_create' recipe.id%}"><button class="btn">Log Meal</button></a>
                    <li class="prewrap">{{ recipe.summary }}</li>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Preparation time: {{ recipe.preparation_minutes }}</li>
                    <li>Cooking time: {{ recipe.cooking_minutes }}</li>
                    <li>Servings: {{ recipe.servings }}</li>
                    <hr />
                    <li><h4>Ingredients:</h4><ul class="list-unstyled">
                    {% for ingredient in ingredients %}
                        <li>{{ingredient.amount}} {{ ingredient.get_size_display }}s: {{ ingredient.ingredient.name }}</li>
                    {% endfor %}
                         </ul></li>
                         <hr />
                    <li><h4>Directions:</h4></li>
                    <li id="directions" class="prewrap text-left">{{ recipe.directions }} {{ average_rating }}</li>
                </ul>
                {% if recipe.user == user %}
                    <a href="{% url 'update' recipe.id %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Edit</button></a>
                   
                    <a href="{% url 'delete_recipe' recipe.id%}">
                        <button  type="button" class="btn" value="Delete">Delete recipe</button></a>
                    </a>
                {% endif %}
                </div> 
            </div>
        </div>


    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3>Nutritional Information</h3>
                <h4 class="my-0 font-weight-normal"></h4>
            </div>
            <div class="card-body">
<!-- here goes the nutritional info/ graphs -->
                <canvas id="myChart" width="400" height="100"></canvas> 
                <br /> 
                <table class="table">
                    <tbody>
                        {% for nutrient, value in recipe.calculate_nutrition.items %}
                            <tr>
                                <th scope="row">{{ nutrient.capitalize }}</th>
                                <td>{{ value|floatformat:2 }}{% if nutrient != 'calorie' %}g{% endif %}</td>
                            </tr> 
                        {% empty %}
                        No nutritional information available
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="notification space-below">
  {% if request.user.is_authenticated and not is_reviewed %}
  <form method="post" action="{% url 'add_review' recipe.id %}">
           {% csrf_token %}

           <h3>Leave a review: </h3>
          <div class="control">
            <div class="select">
                <label>Rating:</label>
            </div>
            <select class="form-control" name="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
          </div>
            
          </select>
          </div>
      <div class="field">
          <label>Comment</label>
          <div class="control">
              <textarea class="textarea form-control" name="comment"></textarea>
          </div>
      </div>
      <br />
      <div class="field">
          <div class="control">
              <button class="btn btn-light is-success">Submit</button>
          </div>
      </div>
  </form>
  {%  elif is_reviewed %}
        <p> You have already reviewed this recipe. </p>
  {% else %}
        <p> Please sign in to add review! </p>
  {% endif%}
<hr>
<h2 class="subtitle">Reviews</h2>
<div class="reviews-wrapper">
 {% for review in reviews %}
    <div class=" notification space-below">
        <p>
            <strong> Date: </strong> {{ review.date_added|date:"Y-m-d"}},
            <span class="fa fa-star{% if review.rating < 1 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if review.rating < 2 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if review.rating < 3 %}-o {% endif %}"></span>
            <span class="fa fa-star{% if review.rating < 4 %}-o {% endif %}" ></span>
            <span class="fa fa-star{% if review.rating < 5 %}-o {% endif %}"></span>
        </p>
        <p>
            {{ review.comment }}
        </br>
       <strong> Reviewer: </strong>
            <a href="{% url 'profile_detail' review.user.id %}">{{ review.user }}</a>
        </p>
        {% if review.user == request.user %} 
        <div class="d-flex">
        <form method="POST" action="{% url 'update_review' review.id %}">
            {% csrf_token %}
            <button type="submit" class="btn" value="Edit">Edit</button>
        </form>
        
        <form action ="{% url 'remove_review' recipe.id review.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn" value="Delete">Delete</button>
        </form>
        </div>
        {% endif%}

    </div>

  {% empty %}
      <div class="notification space-below">
        No reviews yet...
      </div>
  {% endfor %}
  </div>
        
  </div>
</div>
<script>
// jquery function
    $(document).ready(() => {
        $('#directions').text($('#directions').text().replace(/\n/g, '\n\n'))

        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: ['carbohydrate', 'fat', 'protein'],
                datasets: [{
                    labels: 'Nutrients',
                    data: [Math.round(({{recipe.calculate_nutrition|get_item:"carbohydrate"}} + Number.EPSILON) * 100)/ 100, 
                        Math.round(({{recipe.calculate_nutrition|get_item:"fat"}} + Number.EPSILON) * 100)/ 100, 
                        Math.round(({{recipe.calculate_nutrition|get_item:"protein"}} + Number.EPSILON) * 100)/ 100,],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)', 
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                rotation: (0.5 * Math.PI)
            }
        })
    });
</script>
{% endblock %}

ration/templates/recipes/index.html
{% extends 'base.html' %}

{% block content %}
<h3>Recipes List</h3>

  <div class="form-group has-search">
    <span class="fa fa-search form-control-feedback"></span>
    <input id="filter_name" type="text" class="filter form-control" placeholder="Search">
  </div>
  <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" class="advanced">
    Additional Filters <i class="fa fa-angle-down"></i>
  </a>

	<div class="collapse" id="collapseExample">
	<div class="card card-body">    
		<div class="row mb-4">
			<div class="col-md-4">
				<input id="filter_rating" type="number" min="0" max="5" placeholder="Rating" class="filter form-control">
			</div>
			<div class="col-md-4">
				<input id="filter_calorie" type="text" class="filter form-control" type="number" placeholder="Calories">
			</div>

		</div>
		<div class="row">
			<div class="col-md-4">
				<input id="filter_carbohydrate" type="text" class="filter form-control" type="number" placeholder="Carbohydrates">
			</div>
			<div class="col-md-4">
				<input id="filter_fat" type="text" class="filter form-control" type="number" placeholder="Fat">
			</div>
			<div class="col-md-4">
				<input id="filter_protein" type="text" class="filter form-control" type="number" placeholder="Protein">
			</div>
		</div>
	</div>
	</div>
  
{% for recipe in recipes %}

{% with nutrition=recipe.calculate_nutrition rating=recipe.average_rating%}

<div> 
	<div class="card recipe mb-3" data-title="{{ recipe.title }}" data-rating="{{ rating }} "

	{% for key, value in nutrition.items %}
		data-{{ key }}="{{ value }}" 
	{% endfor %}	
	>
		
		<div class="card-body text-sm-left shadow p-3 " >
			<a href="{% url 'detail' recipe.id %}" class="stretched-link">
				{% if recipe.image %}
					<img class="float-left img-thumbnail mr-4" src="{{ recipe.image }}" alt="Image" width="13%">
				
				{% endif%}
			   </a> 
			 
				<h3 class="card-title">{{ recipe }}</h3>
				<h5 class="card-subtitle"><span class="fa fa-star{% if rating < 1 %}-o {% endif %}"></span>
				<span class="fa fa-star{% if rating < 2 %}-o {% endif %}"></span>
				<span class="fa fa-star{% if rating < 3 %}-o {% endif %}"></span>
				<span class="fa fa-star{% if rating < 4 %}-o {% endif %}" ></span>
				<span class="fa fa-star{% if rating < 5 %}-o {% endif %}"></span></h5>
				<p class="card-text">{{ recipe.summary }}</p>
				<button type="button" class="btn btn-secondary" >Details</button></a>
		
		</div>
	</div>
</div>
{% endwith %}	
{% endfor %}



<script>
	$('.filter').on("input", filter)


	function filter(event){
		
		let nameFilter = $('#filter_name').val();
		nameFilter = nameFilter.toLowerCase().trim();
		const ratingFilter = $('#filter_rating').val();
		const calorieFilter = permitMinimum($('#filter_calorie').val());
		const carbohydrateFilter = permitMinimum($('#filter_carbohydrate').val());
		const fatFilter = permitMinimum($('#filter_fat').val());
		const proteinFilter = permitMaximum($('#filter_protein').val());
		$("div.recipe").each((i, e) => {
			title = $(e).data('title').toString().toLowerCase();
			rating = $(e).data('rating');
			calorie = permitMaximum($(e).data('calorie'));
			carbohydrate = permitMaximum($(e).data('carbohydrate'));
			fat = permitMaximum($(e).data('fat'));
			protein = permitMaximum($(e).data('protein'));
			console.log(protein)
			if (rating >= ratingFilter && title.includes(nameFilter) && calorie <= calorieFilter && carbohydrate <= carbohydrateFilter && fat <= fatFilter && protein >= proteinFilter){
				$(e).show();
			} else {
				$(e).hide();
			}
		}
		)
		function permitMinimum(input) {
			return input <= 0 ? Infinity : input
		}
		function permitMaximum(input) {
			return input <= 0 ? 0 : input
		}
	}
</script>
{% endblock content %}

ration/templates/recipes/search.html
{% extends 'base.html' %}


{% block content %}
   {% if searched %}
    <br />
    <h3>You searched for "{{ searched }}".</h3>
    <br />
        {% for recipe in recipes %}
        <div class="card text-sm-left shadow p-3 ">
            <a href="{% url 'detail' recipe.id %}" class="stretched-link">
                </a>
            <div class="card-body">
            <h4 class="card-title">{{ recipe }}</h4>
            <h5 class="card-subtitle"><span class="fa fa-star{% if recipe.average_rating < 1 %}-o {% endif %}"></span>
                <span class="fa fa-star{% if recipe.average_rating < 2 %}-o {% endif %}"></span>
                <span class="fa fa-star{% if recipe.average_rating < 3 %}-o {% endif %}"></span>
                <span class="fa fa-star{% if recipe.average_rating < 4 %}-o {% endif %}" ></span>
                <span class="fa fa-star{% if recipe.average_rating < 5 %}-o {% endif %}"></span></h5>
            <p class="card-text">{{ recipe.summary }}</p>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <h4>You forgot to enter a search form.</h4>
   {% endif %}
    
   
        
{% endblock content %}
    